services:

  agora-bank-db:
    image: postgres:16-alpine
    container_name: agora-bank-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agora-bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d agora-bank"]
      retries: 5
      start_period: 30s
      interval: 10s
      timeout: 5s
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  agora-bank:
    build:
      context: ..
      dockerfile: agora-bank/Dockerfile
    image: agora-bank
    container_name: agora-bank
    depends_on:
      agora-bank-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://agora-bank-db:5432/agora-bank?currentSchema=bank
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  postgres_data: