services:

  agora-bank:
    build:
      context: ..
      dockerfile: agora-bank/Dockerfile
    image: agora-bank
    container_name: agora-bank
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://agora-postgres-db:5432/agora_bank?currentSchema=bank
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin