services:

  rabbitmq:
    image: rabbitmq:4.3.2-management
    container_name: agora-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      retries: 5
      start_period: 30s
      interval: 10s
      timeout: 5s
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16-alpine
    container_name: agora-postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agora-ecosystem-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d agora-ecosystem-db" ]
      retries: 5
      start_period: 30s
      interval: 10s
      timeout: 5s
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "../database/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql"

volumes:
  postgres_data: