services:

  agora-identity:
    build:
      context: ..
      dockerfile: agora-identity/Dockerfile
    networks:
      - agora-network
    image: agora-identity
    container_name: agora-identity
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://agora-ecosystem-db:5432/agora_identity
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

networks:
  agora-network:
    external: true