spring:
  application:
    name: agora-identity

  datasource:
    url: ${db_url:jdbc:postgresql://agora-identity-db:5432/agora-identity?currentSchema=identity}
    username: ${db_username:admin}
    password: ${db_password:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    default-schema: identity
    create-schemas: true