spring:
  application:
    name: agora-identity

  datasource:
    url: ${db_url:jdbc:postgresql://localhost:5432/agora_identity?currentSchema=identity}
    username: ${db_username:admin}
    password: ${db_password:admin}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    default-schema: identity
    create-schemas: true